package com.mobilemoney.billpayment.model;

import java.io.Serializable;
import java.util.List;

import com.mobilemoney.base.util.JSONFormatter;
import com.mobilemoney.common.model.CustomData;
import com.mobilemoney.common.model.MetaData;

/***
 * Class BillPay
 *
 */
public class BillPay implements Serializable {
	private static final long serialVersionUID = 8817178987838661585L;

	// Reference for the payment generated by the service provider
	private String serviceProviderPaymentReference;

	// Reference provided by the requesting organisation
	private String requestingOrganisationTransactionReference;

	// Type of Bill Payment
	private String paymentType;

	// Amount of the Bill that is being paid
	private String amountPaid;

	// Currency of the amount that is being paid
	private String currency;

	// Textual reference provided by the customer paying the bill
	private String customerReference;

	// Originating mobile money provider
	private String requestingOrganisation;

	// Date and time of the request as supplied by the client
	private String requestDate;

	// Amount of the Bill that is being paid
	private String paidAmount;

	// Status of the bill payment
	private String billPaymentStatus;

	// Specific information regarding the bill payment
	private String serviceProviderComment;

	// Specific information that will be included on the notification
	private String serviceProviderNotification;

	// Date and time when the object was created
	private String creationDate;

	// Date and time when the object was modified
	private String modificationDate;

	// Key-value collection enables further reference information to be supplied
	private List<BillReference> billReference;

	// Collection of key/value pairs
	private List<CustomData> customData;

	// Collection of key/value pairs
	private List<MetaData> metadata;

	/***
	 *
	 * @return
	 */
	public String getServiceProviderPaymentReference() {
		return serviceProviderPaymentReference;
	}

	/***
	 *
	 * @param serviceProviderPaymentReference
	 */
	public void setServiceProviderPaymentReference(String serviceProviderPaymentReference) {
		this.serviceProviderPaymentReference = serviceProviderPaymentReference;
	}

	/***
	 *
	 * @return
	 */
	public String getRequestingOrganisationTransactionReference() {
		return requestingOrganisationTransactionReference;
	}

	/***
	 *
	 * @param requestingOrganisationTransactionReference
	 */
	public void setRequestingOrganisationTransactionReference(String requestingOrganisationTransactionReference) {
		this.requestingOrganisationTransactionReference = requestingOrganisationTransactionReference;
	}

	/***
	 *
	 * @return
	 */
	public String getPaymentType() {
		return paymentType;
	}

	/***
	 *
	 * @param paymentType
	 */
	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	/***
	 *
	 * @return
	 */
	public String getAmountPaid() {
		return amountPaid;
	}

	/***
	 *
	 * @param amountPaid
	 */
	public void setAmountPaid(String amountPaid) {
		this.amountPaid = amountPaid;
	}

	/***
	 *
	 * @return
	 */
	public String getCurrency() {
		return currency;
	}

	/***
	 *
	 * @param currency
	 */
	public void setCurrency(String currency) {
		this.currency = currency;
	}

	/***
	 *
	 * @return
	 */
	public String getCustomerReference() {
		return customerReference;
	}

	/***
	 *
	 * @param customerReference
	 */
	public void setCustomerReference(String customerReference) {
		this.customerReference = customerReference;
	}

	/***
	 *
	 * @return
	 */
	public String getRequestingOrganisation() {
		return requestingOrganisation;
	}

	/***
	 *
	 * @param requestingOrganisation
	 */
	public void setRequestingOrganisation(String requestingOrganisation) {
		this.requestingOrganisation = requestingOrganisation;
	}

	/***
	 *
	 * @return
	 */
	public String getRequestDate() {
		return requestDate;
	}

	/***
	 *
	 * @param requestDate
	 */
	public void setRequestDate(String requestDate) {
		this.requestDate = requestDate;
	}

	/***
	 *
	 * @return
	 */
	public String getPaidAmount() {
		return paidAmount;
	}

	/***
	 *
	 * @param paidAmount
	 */
	public void setPaidAmount(String paidAmount) {
		this.paidAmount = paidAmount;
	}

	/***
	 * 
	 * @return
	 */
	public List<BillReference> getBillReference() {
		return billReference;
	}

	/***
	 * 
	 * @param billReference
	 */
	public void setBillReference(List<BillReference> billReference) {
		this.billReference = billReference;
	}

	/***
	 *
	 * @return
	 */
	public List<CustomData> getCustomData() {
		return customData;
	}

	/***
	 *
	 * @param customData
	 */
	public void setCustomData(List<CustomData> customData) {
		this.customData = customData;
	}

	/***
	 *
	 * @return
	 */
	public List<MetaData> getMetadata() {
		return metadata;
	}

	/***
	 *
	 * @param metadata
	 */
	public void setMetadata(List<MetaData> metadata) {
		this.metadata = metadata;
	}

	/***
	 * 
	 * @return
	 */
	public String getBillPaymentStatus() {
		return billPaymentStatus;
	}

	/***
	 * 
	 * @param billPaymentStatus
	 */
	public void setBillPaymentStatus(String billPaymentStatus) {
		this.billPaymentStatus = billPaymentStatus;
	}

	/***
	 * 
	 * @return
	 */
	public String getServiceProviderComment() {
		return serviceProviderComment;
	}

	/***
	 * 
	 * @param serviceProviderComment
	 */
	public void setServiceProviderComment(String serviceProviderComment) {
		this.serviceProviderComment = serviceProviderComment;
	}

	/***
	 * 
	 * @return
	 */
	public String getServiceProviderNotification() {
		return serviceProviderNotification;
	}

	/***
	 * 
	 * @param serviceProviderNotification
	 */
	public void setServiceProviderNotification(String serviceProviderNotification) {
		this.serviceProviderNotification = serviceProviderNotification;
	}

	/***
	 * 
	 * @return
	 */
	public String getCreationDate() {
		return creationDate;
	}

	/***
	 * 
	 * @param creationDate
	 */
	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	/***
	 * 
	 * @return
	 */
	public String getModificationDate() {
		return modificationDate;
	}

	/***
	 * 
	 * @param modificationDate
	 */
	public void setModificationDate(String modificationDate) {
		this.modificationDate = modificationDate;
	}

	/***
	 * Returns JSON object
	 * 
	 * @return
	 */
	public String toJSON() {
		return JSONFormatter.toJSON(this);
	}
}
